const editImageTypes = {
  ADD_NEW_EDITIMAGE_START: "ADD_NEW_EDITIMAGE_START",
  FETCH_EDITIMAGES_START: "FETCH_EDITIMAGES_START",
  SET_EDITIMAGES: "SET_EDITIMAGES",
  DELETE_EDITIMAGE_START: "DELETE_EDITIMAGE_START",
  FETCH_EDITIMAGE_START: "FETCH_EDITIMAGE_START",
  SET_IMAGE: "SET_IMAGE",
};

export default editImageTypes;
