const addressTypes = {
  ADD_NEW_ADDRESS_START: "ADD_NEW_ADDRESS_START",
  FETCH_ADDRESSES_START: "FETCH_ADDRESSES_START",
  SET_ADDRESSES: "SET_ADDRESSES",
  DELETE_ADDRESS_START: "DELETE_ADDRESS_START",
  FETCH_ADDRESS_START: "FETCH_ADDRESS_START",
  SET_ADDRESS: "SET_ADDRESS",
};

export default addressTypes;
